### ISSUE TITLE
Schedule button added function 

### ISSUE THREAD

**Issue by Spectralpt** [joaoalves03/goipvc#16]
When pressed inside the schedule menu the schedule button should re-center the view.

**Comment by rodrigosa7** [comment]
The way to do this is to force a rebuild of the widget, even though I don't like the approach I found a solution by forcing the rebuild (which causes an ugly flash). This should be improved in the future by using another animation or something like that. 

Fixed by commit: https://github.com/joaoalves03/goipvc/commit/f454e66c12710a3f759dc1c28ebe92eb2c3ac0fe
