### ISSUE TITLE
Schedule page weird scroll behaviour 

### ISSUE THREAD

**Issue by CunhaPedro25** [joaoalves03/goipvc#43]
In the schedule page the schedule is overflowing from the actual page, creating a behaviour that shouldn't be expected, as the top bar will change background color while it is not needed.
Schedule should be contained in its own space that has itself scroll, which will remove the top bar behaviour.

**Comment by rodrigosa7** [comment]
This should be fixed by: https://github.com/joaoalves03/goipvc/commit/0960da4920a734f4b3391ae4c5ea4d87a561e08b

We just need to set a default tint for the app bar, which hides the content below. If you want to contain the scroll we need to further investigate on how to do it. Please let me know what you think about it
